Homework 23.6 Jeremy Foley : One Rule

In [1]:
#Download datasets using scikit-learn

from sklearn.datasets import load_iris
dataset = load_iris()
X = dataset.data
Y = dataset.target
#Columns are: Sepal Lenght, Sepal Width, Petal Length, Petal Width

print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [13]:
#This plot shows the original data before implementing One Rule Algorithm
from collections import OrderedDict
import pandas as pd

Iris_data = OrderedDict({'Sepal Length ': X[:,0],
             'Sepal Width': X[:,1],
             'Petal Length': X[:,2],
             'Petal Width': X[:,3],
             'Label': Y})

df = pd.DataFrame(Iris_data)
df

Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0              5.1          3.5           1.4          0.2      0
1              4.9          3.0           1.4          0.2      0
2              4.7          3.2           1.3          0.2      0
3              4.6          3.1           1.5          0.2      0
4              5.0          3.6           1.4          0.2      0
..             ...          ...           ...          ...    ...
145            6.7          3.0           5.2          2.3      2
146            6.3          2.5           5.0          1.9      2
147            6.5          3.0           5.2          2.0      2
148            6.2          3.4           5.4          2.3      2
149            5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [14]:
#The way shown in class was giving me some kind of bound error so I decided to reshape them
import numpy as np

X_0 = np.array( X[:,0] > X[:,0].mean(), dtype = 'int')
X_1 = np.array( X[:,1] > X[:,1].mean(), dtype = 'int')
X_2 = np.array( X[:,2] > X[:,2].mean(), dtype = 'int')
X_3 = np.array( X[:,3] > X[:,3].mean(), dtype = 'int')

X_d0 = X_0.reshape(150,1)
X_d1 = X_1.reshape(150,1)
X_d2 = X_2.reshape(150,1)
X_d3 = X_3.reshape(150,1)
Y_d = Y.reshape(150,1)

In [15]:
#Testing to see if the reshape created the same data frame
Iris_data_d = OrderedDict({'Sepal Length ': X_d0[:,0],
             'Sepal Width': X_d1[:,0],
             'Petal Length': X_d2[:,0],
             'Petal Width': X_d3[:,0],
             'Label': Y})

df = pd.DataFrame(Iris_data_d)
df

Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                0            1             0            0      0
1                0            0             0            0      0
2                0            1             0            0      0
3                0            1             0            0      0
4                0            1             0            0      0
..             ...          ...           ...          ...    ...
145              1            0             1            1      2
146              1            0             1            1      2
147              1            0             1            1      2
148              1            1             1            1      2
149              1            0             1            1      2

[150 rows x 5 columns]

In [16]:
X_final = np.hstack([X_d0,X_d1,X_d2,X_d3,Y_d])

In [17]:
values = []
a = ['Sepal length','Sepal width','Petal length','Petal width']
b = ['Setosa','Versicolor','Virginica']
c = '%'
for i in range(4):
    for j in range(3):
        selection = np.logical_and(X_final[:,i]>.9,X_final[:,4] == j)
        values.append((a[i],b[j],'selected values:', len(X_final[selection]), 'percent', ((len(X_final[selection])/len(X_final[:,i]))*100)))

In [18]:
values

[('Sepal length', 'Setosa', 'selected values:', 0, 'percent', 0.0),
 ('Sepal length',
  'Versicolor',
  'selected values:',
  26,
  'percent',
  17.333333333333336),
 ('Sepal length',
  'Virginica',
  'selected values:',
  44,
  'percent',
  29.333333333333332),
 ('Sepal width',
  'Setosa',
  'selected values:',
  42,
  'percent',
  28.000000000000004),
 ('Sepal width',
  'Versicolor',
  'selected values:',
  8,
  'percent',
  5.333333333333334),
 ('Sepal width',
  'Virginica',
  'selected values:',
  17,
  'percent',
  11.333333333333332),
 ('Petal length', 'Setosa', 'selected values:', 0, 'percent', 0.0),
 ('Petal length',
  'Versicolor',
  'selected values:',
  43,
  'percent',
  28.666666666666668),
 ('Petal length',
  'Virginica',
  'selected values:',
  50,
  'percent',
  33.33333333333333),
 ('Petal width', 'Setosa', 'selected values:', 0, 'percent', 0.0),
 ('Petal width',
  'Versicolor',
  'selected values:',
  40,
  'percent',
  26.666666666666668),
 ('Petal width',
  'Virgini